# Generated by Django 5.0.3 on 2024-03-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('date_enrolled', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
